# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 388fbe3cb71eb898263091d11ca599063fa09d6c73892e79fa9a028e84cb70ddd2ae2483bb120e7c5636d8b7b3b54de256d02aa36907dc3cad11ee2dd016bdb4

test:
  secret_key_base: ba8cad7e3417c264f0f611ae694d9cf8ef9a2a512fafd6cd9a82321629451e3dc4ec6179d35c19943dd16dd6d6e77444e5a37398db28a1b0750d24ad1b24d0ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
